# GitHub Actions configuration file
# This file configures specific behaviors for GitHub Actions workflows

# Allow specific secrets to be used in workflows
allowed_secrets:
  - SNYK_TOKEN

# Suppress specific warnings
suppress_warnings:
  - context_access_snyk_token
