import { CustomLayout } from "@/lib/dashboard-utils"; // Import CustomLayout

export const DEFAULT_LAYOUT: CustomLayout[] = [
  {
    i: "welcome-widget",
    x: 0,
    y: 0,
    w: 6,
    h: 2,
    isVisible: true,
    title: "Welcome",
    widgetType: "welcome-widget",
  },
  {
    i: "daily-focus-widget",
    x: 6,
    y: 0,
    w: 6,
    h: 2,
    isVisible: true,
    title: "Daily Focus",
    widgetType: "daily-focus-widget",
  },
  {
    i: "todo-list",
    x: 0,
    y: 2,
    w: 6,
    h: 3,
    isVisible: true,
    title: "Todo List",
    widgetType: "todo-list",
  },
  {
    i: "goal-progress-widget",
    x: 6,
    y: 2,
    w: 6,
    h: 3,
    isVisible: true,
    title: "Goal Progress",
    widgetType: "goal-progress-widget",
  },
  {
    i: "habit-tracker-widget",
    x: 0,
    y: 5,
    w: 6,
    h: 3,
    isVisible: true,
    title: "Habit Tracker",
    widgetType: "habit-tracker-widget",
  },
  {
    i: "weather-widget",
    x: 6,
    y: 5,
    w: 6,
    h: 3,
    isVisible: true,
    title: "Weather",
    widgetType: "weather-widget",
  },
];
